# Generated by Django 4.0.3 on 2022-04-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created',
        ),
    ]
